CREATE TABLE "Publikationen"."ProducaoBibliografica" ( "id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 20 ), "codPesquisa" INTEGER NOT NULL, "titulo" VARCHAR(500) NOT NULL, "volume" INTEGER NOT NULL, "pagInicial" INTEGER NOT NULL, "pagFinal" INTEGER NOT NULL, "ano" INTEGER NOT NULL, "classificacaoQualis" VARCHAR(50) NOT NULL, "tipo" VARCHAR(50) NOT NULL, "situacao" VARCHAR(50) NOT NULL );
ALTER TABLE "Publikationen"."ProducaoBibliografica" ADD CONSTRAINT "ProducaoBibliografica_PK" PRIMARY KEY ( "id" );
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE "Publikationen"."ProducaoBibliografica"' );
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE "Publikationen"."ProducaoBibliografica"' );

CREATE TABLE "Publikationen"."producaoBibliografica_Base" ( "tituloBase" VARCHAR(500) NOT NULL, "tituloBaseada" VARCHAR(500) NOT NULL );
ALTER TABLE "Publikationen"."producaoBibliografica_Base" ADD CONSTRAINT "producaoBibliografica_Base_PK" PRIMARY KEY ( "tituloBase", "tituloBaseada" );
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE "Publikationen"."producaoBibliografica_Base"' );
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE "Publikationen"."producaoBibliografica_Base"' );

CREATE TABLE PUBLIKATIONEN.PESQUISA ( "codigo" INTEGER NOT NULL, "titulo" VARCHAR(500) NOT NULL );

CREATE TABLE PUBLIKATIONEN.PRODUCAO_BIBLIOGRAFICA_BASE ( "tituloBase" VARCHAR(500) NOT NULL, "tituloBaseada" VARCHAR(500) NOT NULL );
ALTER TABLE PUBLIKATIONEN.PRODUCAO_BIBLIOGRAFICA_BASE ADD CONSTRAINT PRODUCAO_BIBLIOGRAFICA_BASE_PK PRIMARY KEY ( "tituloBase", "tituloBaseada" );
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE PUBLIKATIONEN.PRODUCAO_BIBLIOGRAFICA_BASE' );
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE PUBLIKATIONEN.PRODUCAO_BIBLIOGRAFICA_BASE' );

CREATE TABLE PUBLIKATIONEN.PERIODICO_REVISTA ( ISSN INTEGER NOT NULL );
ALTER TABLE PUBLIKATIONEN.PERIODICO_REVISTA ADD CONSTRAINT PERIODICO_REVISTA_PK PRIMARY KEY ( ISSN );
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE PUBLIKATIONEN.PERIODICO_REVISTA' );
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE PUBLIKATIONEN.PERIODICO_REVISTA' );
